# Generated by Django 2.0.2 on 2019-06-29 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='summary',
            new_name='body',
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 29, 10, 45, 31, 121114, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default=datetime.datetime(2019, 6, 29, 10, 45, 36, 80705, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
